### ISSUE TITLE
Allow to define strong_resource in other places than initializes directory

### ISSUE THREAD

**Issue by BjornMelgaard** [jsonapi-suite/strong_resources#2]
I want to define resource in controller, without `config/initializers/strong_resources.rb`, dont like when all eggs in one basket

```
# no config/initializers/strong_resources.rb file
class ProjectsController < ApplicationController
  strong_resource :project do # NoMethodError: undefined method `[]' for nil:NilClass
    attribute :name, :string
    attribute :user_id, :integer
  end
end
```

**Comment by richmolj** [comment]
The reason we use an initializer is the strong resource definitions can be referenced across multiple controllers. In any case, if you would like to do this, nothing is stopping you except Rails load order (all these controllers need to be `require`d on boot). I'd recommend against this, but if you'd like to do it anyway I believe this is a Rails issue, not a `strong_resources` issue.

**Comment by stevenharman** [comment]
I'm very new to `jsonapi-suite` - like, I only learned it existed earlier today - but I'm very interested. I've used `jsonapi-resources` before and am looking for something both more active and with more seams to customize things. 

Anyhow, when used within `jsonapi-suite`, what about defining the `StrongResource` config w/in the `*Resource` itself? That at least helps to pull together the parameters and attributes used for writing and querying into a single place. Assuming there's no technical reason (or other obvious reason I'm missing due to ignorance and lack of experience with these libraries), what might that look like? How might that be "wired up?"

**Comment by richmolj** [comment]
@stevenharman I think the biggest technical issue - which I *think* is true - is Rails autoloading. Request comes in, but the Resource class hasn't been loaded yet, so it won't have a defined strong resource and will blow up. Other than this I think you could paste the same code into a resource and it might work.

From a library perspective, I lean against it (at least in the short term) just for separation of concerns (API inputs versus a query builder). But I'm not against an optional mixin or something along those lines if you overcame the technical issues.

**Comment by stevenharman** [comment]
@richmolj TL;DR: I think the autoloading can be solved. I also believe I can make an argument for pulling some of these things together into a single (or at least fewer) locations.

I'm having a little trouble understanding how `strong_resources` gets into the life cycle of a request, but it seems like a request would come in, and then be routed to a controller. The controller "knows" about the resource type via the `jsonapi resource: FooResource`. Meaning the Rails autoloader will load that constant, and if the `StrongResource` definition is in that resource file (e.g., in `app/resources/foo_resource.rb`), then the config has also been loaded and is available. At that point, `strong_resources` and `apply_strong_params` and it's business as usual. Yeah?

As for SoC concerns, IMO/IME defining what a resource _is_ in one place gives a more complete picture of the resource. Defining the valid attributes (readable vs writeable), relations, and query facilities (which are based on those same attributes) for a resource in three disparate files/classes feels... disconnected. I'm not sure shoving them all into the same file is ideal either, but maybe there's a better line to be drawn?

**Comment by richmolj** [comment]
I think the issue with autoloading would be with sideposting, which would need to load a nested resource. But I could definitely be wrong, things have changed a lot since the last time I tried.

> IMO/IME defining what a resource is in one place

I think this is where I have a different perspective. Right now we have three concepts:

* API Inputs (strong resources)
* API outputs (serializers)
* Resources (coordination between API and model layer)

I'm wary of conflating these into one single "resource" concept. Right now, you can swap all of these depending on different contexts - an internal-only endpoint might accept different API inputs but reuse the same Resource (or vice versa) for instance. I've also had use cases where the Resource I use in my main controller is not the Resource I want to use when sideloading/sideposting. Plus, it would feel a little odd to be to have inputs in the Resource but outputs in separate serializer files (and too-big if everything were in the same file).

It's absolutely possible the swappability will be such an edge case it's not worth organizing our DSL to accommodate it, and we should instead shoot for a better "default use case". I'm definitely open to that, just in "time will tell" mode. I'd love to see you take a stab at it and see what you come up with.

As a side note, one thing I'd like to add soon is "field generators", so when you are adding a field the generator automatically writes to all the correct files for you. This might be something that at least helps when dealing with multiple files.

**Comment by stevenharman** [comment]
> I'm wary of conflating these into one single "resource" concept.

Same. Which is why I mentioned _"I'm not sure shoving them all into the same file is ideal either, but maybe there's a better line to be drawn?"_ Maybe simply getting `StrongResources` out of an initializer and into a file and class "closer" to the serializer and resource definitions would be good? An off the cuff idea:

```
app/
    resources/
              foo_resource.rb
              foo_serializer.rb
              foo_params.rb
```

or maybe

```
app/
    resources/
              foo/
                  resource.rb
                  serializer.rb
                  input_params.rb
```

The exact names and structure are just to illustrate organizing things a bit more cohesively, while preserving the ability to mix and match. e.g., adding a `foo_summary_serializer.rb` that's used in some cases.

Anyhow, I think once we can confirm that getting the StrongResources out of an initializer will work, then re-organzing the structure of the files and classes would be a simpler step forward.

**Comment by stevenharman** [comment]
A quick experiment (I don't have an up and running JSONAPI Suite app, or I'd do it now) would be to refer to change the StrongResource API a bit to instead reference the constant in the controller, rather than a symbol.

```ruby
strong_resource FooParams

# or

strong_resource :foo   #=> by default this looks up the constant `FooParams` starting in the current namespace and going upward.

# with an option to override

strong_resource :foo, class_name: 'FooSummaryParams'
```

Thoughts?

**Comment by richmolj** [comment]
If the intent is just to deal with autoloading, I think we could do the same without a change to the API. Or were you going for something else with the above?

I think an eventual "merged resource" could look something like

```ruby
class PersonResource < ApplicationResource
  attribute :first_name, :string # adds SR and serializer under-the-hood

  # when given a block, it drops-down to jsonapi-rb serialization
  attribute :full_name do
    [@object.first_name, @object.last_name].join(' ')
  end

  # we still need to support stuff like this
  attribute :foo, only: [:create]
end
```

I tend to think such a combined interface would be less-desirable, but happy to be proven wrong or at least give an alternative. In the short term this could be some `CombinedResource` optional mixin.

**Comment by richmolj** [comment]
@stevenharman still interested in this? Maybe we could move to a separate issue to make sure it's on our roadmap in some form.

**Comment by stevenharman** [comment]
I am still interested, but have been focused on some other things lately. But I expect to start using `jsonapi-suite` in earnest very soon. A new issue sounds 👍.

**Comment by stevenharman** [comment]
I'm finally getting back to `jsonapi-suite` and wanted to look at how to avoid the initializers to define the `StrongResource`s. I'm happy to open a new Issue if you like (as we said), but there's a lot of good context here, and my current goal is still exactly the title of this issue. So...

> If the intent is just to deal with autoloading, I think we could do the same without a change to the API. 

I'm not sure what you have in mind, but when spelunking the code, it looks like we might be able to change the way that `StrongResources::find` works. It currently expects `StrongResources.config.strong_resources` (which is hash) to already have the `name` of the `StrongResource` in the hash. With the value being the definition of strong resource.

But we could change this to first check the `StrongResources.config.strong_resources` hash for the given name. But if it's missing, try to resolve a constant, based on the given `name`. Rails could then auto-load that constant. If the constant is loaded, we'd need to call/evaluate it so it can setup the strong resource, and then push that definition into `StrongResources.config.strong_resources`. If the constant can't be loaded (b/c it doesn't exist), we could rescue and raise the `UnregisteredResource` as we do today.

This might all be made a little easier with some tweaks to the controller's `strong_resource(name, opts = {}, &blk)` method to allow tuning the constant to look up for the name. For example to allow namespacing the constants. But we can figure that out later.

A back-of-the-napkin sketch of how this might work:

```ruby
# app/controllers/employee_controller.rb
class EmployeesController < ApplicationController
  jsonapi resource: EmployeeResource

  strong_resource :employee
end

# app/resources/employee_params.rb
class EmployeeParams < StrongResources::Params
  configure do
    attribute :first_name, :string
    attribute :last_name, :string
    attribute :age, :integer
  end
end

# strong_resources/lib/strong_resources.rb
module StrongResources

  # ...

  def self.find(name)
    found = config.strong_resources[name]
    found ||= find_params_class(name)
    raise UnregisteredResource.new(name) unless found
    found
  end

  def self.find_params_class(name)
    klass = "#{String(name).camelize}Params".safe_constantize
    return unless klass

    { name: name, base: klass.configuration }.tap do |resource|
      config.strong_resource[name] = resource
    end
  end
end

# strong_resources/lib/strong_resources/params.rb
module StrongResources
  class Params
    def self.configure(&blk)
      @config_block = blk
    end

    def self.configuration
      @config_block
    end
  end
end
```

Anyhow, is this in line with what you'd imaged? Or something that would work?

**Comment by richmolj** [comment]
I think the route you are heading down is really interesting. My primary concern is to make this opt-in and still support stuffing everything in an initializer. But the file structure I think is a great idea - would love to support it and see which users prefer. I could actually see going down this route myself, which is pretty exciting.

One thing to consider is adding custom types. I'm thinking you'd still do this in an initializer, so the types can be shared across resources.

Another note is to consider the concept of parent/composable resources (like FactoryBot). Don't think it prohibits anything just noting the issue.

I can't think of any overall problems with this strategy, as long as we make it simple to opt-in. Would love to see you take this and run with it!
